<script>
	import logo from '$lib/assets/logo_1024.png';
	import Prose from '$lib/components/Prose.svelte';
</script>

<svelte:head>
	<title>About</title>
	<meta name="description" content="About this app" />
</svelte:head>

<Prose>
	<h1>About this app</h1>
	<p>This is my about page</p>
</Prose>

<div class="flex">
	<p
		class="
    flex items-center
    text-sm italic
    text-gray-600
    "
	>
		Image generated by ai art generator when prompted "vector image of blue mint soda from an anime"
	</p>

	<picture>
		<source srcset={logo} type="image/webp" />
		<img src={logo} alt="logo" width="256" height="256" />
	</picture>
</div>
